import boto3, json
from loguru import logger

session = boto3.Session(profile_name='', region_name='eu-west-1')
client = session.client('iotwireless')

response = client.create_network_analyzer_configuration(
    Name='AutoGenerated_with_script',
    TraceContent={
        'WirelessDeviceFrameInfo': 'ENABLED',
        'LogLevel': 'INFO'
    },
    WirelessDevices=[
        '75366fd3-35d9-4ea0-b4f7-579974ed9655',
        'e6837a6c-282e-458d-ac65-d209a68fa866',
        'c4da6805-8216-4591-a36e-7cac79c75534',
    ],
    WirelessGateways=[
        '2da55bb2-e394-4d47-81f5-5cdf82a5e0f8',
    ],
    Description='Test script for NA creation',
)
